name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:   

jobs:
  CI:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: 18.16.1
        
 
