name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:   

jobs:
  CI:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: 18.16.1

      - name: Setup Mocha and test packages
        run: |
          cd src;
          npm install -g mocha;
          npm install;

      - name: Run tests
        run: |
          cd src;
          npm test;
      
      - name: Build docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: |
            dimitrifinger/tibia-search:v1
            dimitrifinger/tibia-search:latest
        
 
